[package]
name = "mhrice"
version = "0.1.0"
authors = ["Weiyi Wang <wwylele@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
murmur3 = "0.5"
zstd = "0.7"
once_cell = "1.5"
structopt = "0.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
typed-html = { git = "https://github.com/bodil/typed-html.git" }
chrono = "0.4"
rusoto_core = "0.46"
rusoto_s3 = "0.46"
futures = "0.3"
walkdir = "2"
tokio = { version = "1", features = ["fs"] }
tokio-util = { version = "0.6", features = ["codec"] }
regex = "1.4"
rayon = "1.5"
bitflags = "1.2"
nalgebra-glm = { version = "0.12", features = ["serde-serialize"]}
glium = "0.29"
png = "0.16"
ordered-float = "2.1"
half = "1.7"
compress = "0.2"

[build-dependencies]
built = { version = "0.4", features = ["git2"] }
cmake = "0.1"
